
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Login extends javax.swing.JFrame {

    public static String users_update = "";
    ArrayList<Alumnos> students = new ArrayList();
    ArrayList<tutorias> tutors = new ArrayList();
    int estudiante;

    String userrs = "", update_users = "";
    Alumnos seleccionado;

    public Login() {
        initComponents();
        setSize(550, 600);
        setResizable(false);
        setTitle(" Acompañamiento estudiantil UNITEC");
        this.setLocationRelativeTo(null);
        DefaultTableModel modeloo = (DefaultTableModel) tabi1.getModel();

        tabi1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = tabi1.rowAtPoint(e.getPoint());
                int columna_points = 2;
                if (fila_point > -1) {
                    users_update = (String) modeloo.getValueAt(tabi1.getSelectedRow(), 0);
                    modifyStudents.pack();
                    modifyStudents.setModal(true);
                    //RegistroAlumnos.setLocationRelativeTo(this);
                    modifyStudents.setVisible(true);

                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGIIN = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tf_user1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_password1 = new javax.swing.JPasswordField();
        bt_iniciar1 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();
        listarAlumnos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        Cb_Alumnos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegistroAlumnos = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_edad1 = new javax.swing.JTextField();
        tf_carrera1 = new javax.swing.JTextField();
        tf_lugar1 = new javax.swing.JTextField();
        tf_numeroCuenta1 = new javax.swing.JTextField();
        tf_usuario1 = new javax.swing.JTextField();
        cb_tipoAlumno1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        bt_registrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        MenuTutores = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        bt_list = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        bt_modificar1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        MenuEstudiantes = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        bt_modificar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        bt_listar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        bt_examenesPendientes = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        bt_examenesResueltos = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        bt_regresar = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        bt_reservar = new javax.swing.JButton();
        bt_exit1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        fondoAlumno = new javax.swing.JLabel();
        ModificarAlumnos = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        cb_estudiantes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabi1 = new javax.swing.JTable();
        fondoModi = new javax.swing.JLabel();
        CrearExamen = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        tf_clase = new javax.swing.JTextField();
        tf_requerido = new javax.swing.JTextField();
        tf_tema = new javax.swing.JTextField();
        tf_puntaje = new javax.swing.JTextField();
        bt_crearExamen = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        verExamenesPendientes = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableExams = new javax.swing.JTable();
        ReservarTutorias = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tf_hora = new javax.swing.JTextField();
        tf_aula = new javax.swing.JTextField();
        tf_dia = new javax.swing.JTextField();
        tf_class = new javax.swing.JTextField();
        tf_mes = new javax.swing.JTextField();
        tf_year = new javax.swing.JTextField();
        tf_topic = new javax.swing.JTextField();
        bt_reservation = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Listar_tutores = new javax.swing.JDialog();
        Cb_tutores = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablee = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        modifyStudents = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        bt_charge = new javax.swing.JButton();
        txt_password = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_cuenta = new javax.swing.JTextField();
        txt_lugar = new javax.swing.JTextField();
        txt_carrera = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txt_nivel = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        bt_modify = new javax.swing.JButton();
        wallPaper = new javax.swing.JLabel();
        cb_crearAlumno = new javax.swing.JButton();
        cb_login = new javax.swing.JButton();
        cb_crearExamen = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        LOGIIN.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("Iniciar Sesion");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, 30));
        jPanel2.add(tf_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 30));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setText("Contraseña");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 80, 30));
        jPanel2.add(tf_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 120, 30));

        bt_iniciar1.setBackground(new java.awt.Color(51, 255, 51));
        bt_iniciar1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt_iniciar1.setText("Iniciar Sesion");
        bt_iniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciar1MouseClicked(evt);
            }
        });
        jPanel2.add(bt_iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 140, 70));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/iniciar-sesion (1).png"))); // NOI18N
        jPanel2.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 510, 540));

        LOGIIN.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        listarAlumnos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cb_Alumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cb_AlumnosItemStateChanged(evt);
            }
        });
        Cb_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_AlumnosActionPerformed(evt);
            }
        });
        jPanel3.add(Cb_Alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 120, 40));

        tabi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de nacimiento", "Numero de cuenta", "Usuario", "Contraseña", "Conocimiento acumulado", "Nivel de aprendizaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabi);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 820, 210));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lista de Alumnos");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/white2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        listarAlumnos.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RegistroAlumnos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Usuario");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 90, 40));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Numero de cuenta");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 120, 40));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Lugar de nacimiento");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 40));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Edad");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, 40));

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Carrera");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, 40));

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Contraseña");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 40));

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Nombre");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, 40));
        jPanel5.add(tf_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 120, 30));
        jPanel5.add(tf_edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, 30));
        jPanel5.add(tf_carrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, 30));
        jPanel5.add(tf_lugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, 30));
        jPanel5.add(tf_numeroCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 120, 30));
        jPanel5.add(tf_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 30));

        cb_tipoAlumno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tutores", "Estudiantes normales" }));
        cb_tipoAlumno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_tipoAlumno1MouseClicked(evt);
            }
        });
        cb_tipoAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoAlumno1ActionPerformed(evt);
            }
        });
        jPanel5.add(cb_tipoAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 110, 40));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tipo de alumno");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 40));
        jPanel5.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 120, 30));

        bt_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/registro.png"))); // NOI18N
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        jPanel5.add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 120, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/hacia-atras.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 120, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/estudiante.png"))); // NOI18N
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        RegistroAlumnos.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        MenuTutores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MenuTutores.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bt_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/lista.png"))); // NOI18N
        bt_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listMouseClicked(evt);
            }
        });
        MenuTutores.getContentPane().add(bt_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 60));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Bienvenido al menu para tutores");
        MenuTutores.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel40.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Listar datos");
        MenuTutores.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 40));

        bt_modificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/editar (1).png"))); // NOI18N
        bt_modificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar1MouseClicked(evt);
            }
        });
        MenuTutores.getContentPane().add(bt_modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, 70));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("Modifcar Datos del tutor");
        MenuTutores.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/white2.png"))); // NOI18N
        MenuTutores.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 1000, 710));

        MenuEstudiantes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/editar (1).png"))); // NOI18N
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarMouseClicked(evt);
            }
        });
        jPanel6.add(bt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, 70));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField1.setText("Bienvenido al menu de estudiantes");
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 270, 40));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 153, 0));
        jTextField2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField2.setText("Regresar");
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, -1, -1));

        bt_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/lista.png"))); // NOI18N
        bt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listarMouseClicked(evt);
            }
        });
        jPanel6.add(bt_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 60, 70));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Modifcar Datos del alumno");
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        bt_examenesPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/libro-electronico.png"))); // NOI18N
        bt_examenesPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_examenesPendientesMouseClicked(evt);
            }
        });
        jPanel6.add(bt_examenesPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 80, 60));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Listado de alumnos y alumnos normales");
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        bt_examenesResueltos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/resultado.png"))); // NOI18N
        jPanel6.add(bt_examenesResueltos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 60));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Ver examenes pendientes");
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        bt_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/hacia-atras.png"))); // NOI18N
        bt_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_regresarMouseClicked(evt);
            }
        });
        jPanel6.add(bt_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 80, 60));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Rservar tutorias");
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        bt_reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/libro.png"))); // NOI18N
        bt_reservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_reservarMouseClicked(evt);
            }
        });
        jPanel6.add(bt_reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 80, 60));

        bt_exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/salida.png"))); // NOI18N
        bt_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exit1MouseClicked(evt);
            }
        });
        jPanel6.add(bt_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 110, 40));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("Ver examenes resueltos");
        jPanel6.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        fondoAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/altavoz.png"))); // NOI18N
        jPanel6.add(fondoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 740));

        MenuEstudiantes.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ModificarAlumnos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_estudiantes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_estudiantesItemStateChanged(evt);
            }
        });
        jPanel7.add(cb_estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 110, 50));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Lista de estudiantes");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 120, 40));

        tabi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de nacimiento", "Numero de cuenta", "Usuario", "Contraseña", "Conocimiento acumulado", "Nivel de aprendizaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabi1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabi1);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 820, 210));

        fondoModi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/white2.png"))); // NOI18N
        jPanel7.add(fondoModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        ModificarAlumnos.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 780));

        CrearExamen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tf_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));
        jPanel1.add(tf_requerido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 90, -1));
        jPanel1.add(tf_tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, -1));

        tf_puntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_puntajeActionPerformed(evt);
            }
        });
        jPanel1.add(tf_puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        bt_crearExamen.setText("Crear examen");
        bt_crearExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearExamenMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crearExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 40));

        jLabel25.setText("Clase");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel26.setText("Conocimiento Requerido");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel27.setText("Tema");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, 20));

        jLabel28.setText("Puntaje");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        CrearExamen.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        verExamenesPendientes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableExams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Tema", "Conocimiento", "Puntaje"
            }
        ));
        jScrollPane3.setViewportView(tableExams);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 460, 210));

        verExamenesPendientes.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ReservarTutorias.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("Hora");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel31.setText("Aula");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel32.setText("Dia");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel33.setText("Clase");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel34.setText("Mes");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel35.setText("Año");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel36.setText("Tema");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
        jPanel9.add(tf_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 80, -1));
        jPanel9.add(tf_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 80, -1));
        jPanel9.add(tf_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 80, -1));

        tf_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_classActionPerformed(evt);
            }
        });
        jPanel9.add(tf_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 80, -1));
        jPanel9.add(tf_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, -1));
        jPanel9.add(tf_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 80, -1));
        jPanel9.add(tf_topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 80, -1));

        bt_reservation.setText("reservar");
        bt_reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_reservationMouseClicked(evt);
            }
        });
        jPanel9.add(bt_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 140, 50));
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 610, 650));

        ReservarTutorias.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Listar_tutores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cb_tutores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cb_tutoresItemStateChanged(evt);
            }
        });
        Cb_tutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_tutoresActionPerformed(evt);
            }
        });
        Listar_tutores.getContentPane().add(Cb_tutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 120, 50));

        jLabel38.setText("Lista tutores");
        Listar_tutores.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 50));

        tablee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nacmiento", "Numerp de cuenta", "Usuario", "Contraseña", "Ganancias", "Tutorias dadas", "nivel de enseñanza"
            }
        ));
        jScrollPane4.setViewportView(tablee);

        Listar_tutores.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 550, 170));
        Listar_tutores.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 641));

        modifyStudents.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        modifyStudents.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelNombre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        labelNombre.setText("Nombre");
        modifyStudents.getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, 30));

        jLabel43.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel43.setText("Edad");
        modifyStudents.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel44.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel44.setText("Carrera");
        modifyStudents.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel45.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel45.setText("Lugar de nacimiento");
        modifyStudents.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel46.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel46.setText("Numero de cuenta");
        modifyStudents.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel47.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel47.setText("Usuario");
        modifyStudents.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 50, 30));

        jLabel41.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel41.setText("Nivel de aprendizaje");
        modifyStudents.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        bt_charge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/editar (1).png"))); // NOI18N
        bt_charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_chargeMouseClicked(evt);
            }
        });
        modifyStudents.getContentPane().add(bt_charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 100, 70));
        modifyStudents.getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 80, -1));
        modifyStudents.getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, -1));
        modifyStudents.getContentPane().add(txt_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, -1));
        modifyStudents.getContentPane().add(txt_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, -1));
        modifyStudents.getContentPane().add(txt_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 80, -1));
        modifyStudents.getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 80, -1));
        modifyStudents.getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, -1));

        jLabel42.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel42.setText("Contraseña");
        modifyStudents.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));
        modifyStudents.getContentPane().add(txt_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 80, -1));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Cargar Datos");
        modifyStudents.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 30));

        bt_modify.setText("Modificar");
        bt_modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modifyMouseClicked(evt);
            }
        });
        modifyStudents.getContentPane().add(bt_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 110, 70));

        wallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/white2.png"))); // NOI18N
        modifyStudents.getContentPane().add(wallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_crearAlumno.setBackground(new java.awt.Color(0, 0, 255));
        cb_crearAlumno.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        cb_crearAlumno.setText("Crear alumno");
        cb_crearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_crearAlumnoMouseClicked(evt);
            }
        });
        getContentPane().add(cb_crearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 40));

        cb_login.setBackground(new java.awt.Color(255, 0, 0));
        cb_login.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        cb_login.setText("Login");
        cb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_loginMouseClicked(evt);
            }
        });
        getContentPane().add(cb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 120, 40));

        cb_crearExamen.setBackground(new java.awt.Color(255, 255, 0));
        cb_crearExamen.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        cb_crearExamen.setText("Crear Examen");
        cb_crearExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_crearExamenMouseClicked(evt);
            }
        });
        getContentPane().add(cb_crearExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 150, 30));

        bt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/salida.png"))); // NOI18N
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
        });
        getContentPane().add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 110, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iamges/menu.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipoAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoAlumno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipoAlumno1ActionPerformed

    private void cb_tipoAlumno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_tipoAlumno1MouseClicked

    }//GEN-LAST:event_cb_tipoAlumno1MouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        // TODO add your handling code here:

        String name = tf_nombre1.getText();
        String edad = tf_edad1.getText();
        String carrera = tf_carrera1.getText();
        String lugar = tf_lugar1.getText();
        String numero = tf_numeroCuenta1.getText();
        String usuario = tf_usuario1.getText();
        String password = tf_password.getText();
        String tipoAlumno = "";
        if (cb_tipoAlumno1.getSelectedItem().toString().equals("Tutores")) {
            int ense = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese nivel de enseñanza del tutor"));
            tipoAlumno = "Tutores";
            students.add(new tutores(0, 0, ense, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno));
            Alumnos L = new tutores(0, 0, ense, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno);
            students.add(L);

            tf_nombre1.setText("");
            tf_edad1.setText("");
            tf_carrera1.setText("");
            tf_lugar1.setText("");
            tf_numeroCuenta1.setText("");
            tf_usuario1.setText("");
            tf_password.setText("");

            DefaultComboBoxModel st = (DefaultComboBoxModel) Cb_tutores.getModel();
            st.addElement(L);
            Cb_tutores.setModel(st);
            JOptionPane.showMessageDialog(this, " Tutor creado con exito");

        } else {
            int opi = Integer.parseInt(JOptionPane.showInputDialog(" Seleccione que tipo de estudiante es, \n"
                    + " 1. Ingenieros,\n"
                    + " 2. Licenciados,\n"
                    + " 3. Medicos"));
            switch (opi) {
                case 1:
                    tipoAlumno = "Estudiante Normal";
                    int apren = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese nivel de aprendizaje del estudiante ingeniero"));
                    students.add(new Ingenieros(0, 0, 0, apren, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno));

                    Alumnos L = new Ingenieros(0, 0, 0, apren, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno);
                    students.add(L);
                    DefaultComboBoxModel st = (DefaultComboBoxModel) Cb_Alumnos.getModel();
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_estudiantes.getModel();

                    st.addElement(L);
                    m.addElement(L);
                    Cb_Alumnos.setModel(st);
                    cb_estudiantes.setModel(m);
                    JOptionPane.showMessageDialog(this, " Alumno ingeniero creado con exito");

                    tf_nombre1.setText("");
                    tf_edad1.setText("");
                    tf_carrera1.setText("");
                    tf_lugar1.setText("");
                    tf_numeroCuenta1.setText("");
                    tf_usuario1.setText("");
                    tf_password.setText("");

                    break;

                case 2:
                    tipoAlumno = "Estudiante normal";
                    int aprend = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese nivel de aprendizaje del estudiante licenciado"));
                    students.add(new Licenciados(0, 0, aprend, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno));

                    L = new Licenciados(0, 0, aprend, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno);
                    students.add(L);

                    DefaultComboBoxModel sd = (DefaultComboBoxModel) Cb_Alumnos.getModel();
                    DefaultComboBoxModel m1 = (DefaultComboBoxModel) cb_estudiantes.getModel();
                    sd.addElement(L);
                    m1.addElement(L);
                    Cb_Alumnos.setModel(sd);
                    cb_estudiantes.setModel(m1);

                    JOptionPane.showMessageDialog(this, " Alumno licenciado creado con exito");

                    tf_nombre1.setText("");
                    tf_edad1.setText("");
                    tf_carrera1.setText("");
                    tf_lugar1.setText("");
                    tf_numeroCuenta1.setText("");
                    tf_usuario1.setText("");
                    tf_password.setText("");

                    break;

                case 3:
                    tipoAlumno = "Estudiante Normal";
                    int apre = Integer.parseInt(JOptionPane.showInputDialog(" Ingrese nivel de aprendizaje del estudiante medico"));
                    students.add(new Medicos(0, 0, 0, apre, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno));

                    L = new Medicos(0, 0, 0, apre, name, carrera, lugar, usuario, password, numero, edad, tipoAlumno);
                    students.add(L);

                    DefaultComboBoxModel sp = (DefaultComboBoxModel) Cb_Alumnos.getModel();
                    DefaultComboBoxModel m2 = (DefaultComboBoxModel) cb_estudiantes.getModel();
                    sp.addElement(L);
                    m2.addElement(L);
                    Cb_Alumnos.setModel(sp);
                    cb_estudiantes.setModel(m2);

                    tf_nombre1.setText("");
                    tf_edad1.setText("");
                    tf_carrera1.setText("");
                    tf_lugar1.setText("");
                    tf_numeroCuenta1.setText("");
                    tf_usuario1.setText("");
                    tf_password.setText("");

                    JOptionPane.showMessageDialog(this, " Alumno medico creado con exito");

                    break;
                default:
                    JOptionPane.showMessageDialog(this, " Opcion Incorrecta");
            }

        }


    }//GEN-LAST:event_bt_registrarMouseClicked

    private void Cb_AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_AlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_AlumnosActionPerformed

    private void Cb_AlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cb_AlumnosItemStateChanged
        if (evt.getStateChange() == 2) {
            EstudiantesNormales s = (EstudiantesNormales) Cb_Alumnos.getSelectedItem();
            Object[] newrow = {
                s.getNombre(), s.getEdad(), s.getCarrera(), s.getLugar(), s.getCuenta(), s.getUsuario(), s.getPassword(), s.getConocimiento(), s.getAprendizaje()
            };

            DefaultTableModel modelo = (DefaultTableModel) tabi.getModel();
            modelo.addRow(newrow);
            tabi.setModel(modelo);
        }

    }//GEN-LAST:event_Cb_AlumnosItemStateChanged

    private void cb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_loginMouseClicked
        LOGIIN.pack();
        LOGIIN.setModal(true);
        LOGIIN.setLocationRelativeTo(this);
        LOGIIN.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cb_loginMouseClicked

    private void cb_crearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crearAlumnoMouseClicked
        RegistroAlumnos.pack();
        RegistroAlumnos.setModal(true);
        RegistroAlumnos.setLocationRelativeTo(this);
        RegistroAlumnos.setVisible(true);

    }//GEN-LAST:event_cb_crearAlumnoMouseClicked

    private void bt_iniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciar1MouseClicked

        String nombre = tf_user1.getText();
        String pass = tf_password1.getText();
        boolean tipo = false;

        for (int i = 0; i < students.size(); i++) {
            if (students.get(i).getUsuario().equals(nombre) && students.get(i).getPassword().equals(pass)) {
                if (students.get(i) instanceof tutores) {
                    MenuTutores.pack();
                    MenuTutores.setModal(true);
                    MenuTutores.setLocationRelativeTo(this);
                    MenuTutores.setVisible(true);

                } else if (students.get(i) instanceof EstudiantesNormales) {
                    MenuEstudiantes.pack();
                    MenuEstudiantes.setModal(true);
                    MenuEstudiantes.setLocationRelativeTo(this);
                    MenuEstudiantes.setVisible(true);
                    estudiante = i;

                }

                tipo = true;
                tf_user1.setText("");
                tf_password1.setText("");
                break;
            }

        }

        if (tipo == false) {
            JOptionPane.showMessageDialog(this, " Usuario o contraseña incorrecta");
            tf_user1.setText("");
            tf_password1.setText("");

        }

    }//GEN-LAST:event_bt_iniciar1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        RegistroAlumnos.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarMouseClicked
        MenuEstudiantes.setVisible(false);
        listarAlumnos.pack();
        listarAlumnos.setModal(true);
        listarAlumnos.setLocationRelativeTo(this);
        listarAlumnos.setVisible(true);
    }//GEN-LAST:event_bt_listarMouseClicked

    private void bt_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_regresarMouseClicked
        MenuEstudiantes.setVisible(false);
    }//GEN-LAST:event_bt_regresarMouseClicked

    private void cb_estudiantesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_estudiantesItemStateChanged
        if (evt.getStateChange() == 2) {
            EstudiantesNormales s = (EstudiantesNormales) cb_estudiantes.getSelectedItem();
            Object[] newrow = {
                s.getNombre(), s.getEdad(), s.getCarrera(), s.getLugar(), s.getCuenta(), s.getUsuario(), s.getPassword(), s.getConocimiento(), s.getAprendizaje()
            };

            DefaultTableModel modelo = (DefaultTableModel) tabi1.getModel();
            modelo.addRow(newrow);
            tabi.setModel(modelo);
        }
    }//GEN-LAST:event_cb_estudiantesItemStateChanged

    private void bt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseClicked
        MenuEstudiantes.setVisible(false);
        ModificarAlumnos.pack();
        ModificarAlumnos.setModal(true);
        ModificarAlumnos.setLocationRelativeTo(this);
        ModificarAlumnos.setVisible(true);
    }//GEN-LAST:event_bt_modificarMouseClicked
    int filas;
    private void tabi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabi1MouseClicked

    }//GEN-LAST:event_tabi1MouseClicked

    private void tf_puntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_puntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_puntajeActionPerformed

    private void bt_crearExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearExamenMouseClicked

        String asignatura, knowi, topic, marcador;
        asignatura = tf_clase.getText();
        knowi = tf_requerido.getText();
        topic = tf_tema.getText();
        marcador = tf_puntaje.getText();

        int knowledge = Integer.parseInt(knowi);
        int points = Integer.parseInt(marcador);
        Object[] exmanes = {asignatura, knowledge, topic,};
        DefaultTableModel modelo = (DefaultTableModel) tableExams.getModel();
        modelo.addRow(exmanes);
        tableExams.setModel(modelo);
        ((EstudiantesNormales) students.get(estudiante)).getExams().add(new Examenes(asignatura, topic, knowledge, points));
        JOptionPane.showMessageDialog(this, " Examenes agregado a alumnos exitosamente");


    }//GEN-LAST:event_bt_crearExamenMouseClicked

    private void bt_examenesPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_examenesPendientesMouseClicked
        MenuEstudiantes.setVisible(false);
        verExamenesPendientes.pack();
        verExamenesPendientes.setModal(true);
        verExamenesPendientes.setLocationRelativeTo(this);
        verExamenesPendientes.setVisible(true);
    }//GEN-LAST:event_bt_examenesPendientesMouseClicked

    private void cb_crearExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crearExamenMouseClicked

        CrearExamen.pack();
        CrearExamen.setModal(true);
        CrearExamen.setLocationRelativeTo(this);
        CrearExamen.setVisible(true);
    }//GEN-LAST:event_cb_crearExamenMouseClicked

    private void bt_reservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reservarMouseClicked


    }//GEN-LAST:event_bt_reservarMouseClicked

    private void tf_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_classActionPerformed

    private void bt_reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_reservationMouseClicked

        boolean flag = true;
        String ho = tf_hora.getText();
        String au = tf_aula.getText();
        String di = tf_dia.getText();
        String clase = tf_clase.getText();
        String mes = tf_mes.getText();
        String añ = tf_year.getText();
        String tema = tf_tema.getText();

        tutores tutor = ((tutores) Cb_tutores.getSelectedItem());

        int hora = Integer.parseInt(ho);
        int aula = Integer.parseInt(au);
        int año = Integer.parseInt(añ);
        int dia = Integer.parseInt(di);

        for (int i = 0; i < tutors.size(); i++) {
            if (tutors.get(i).getHora() == hora && tutors.get(i).getAula() == aula && tutors.get(i).getDia() == dia && tutors.get(i).getClase().equals(clase)
                    && tutors.get(i).getHora() == hora && tutors.get(i).getAula() == aula && tutors.get(i).getClase() == clase) {
                JOptionPane.showMessageDialog(this, "Ya existe esa tutoria, se le añadirá un cupo");
                tutors.get(i).getTutorias().add(tutors.get(estudiante));

            } else {
                for (int j = 0; j < tutors.size(); j++) {
                    if (tutors.get(j) instanceof tutorias) {
                        if (tutors.get(i).equals(tutor.getNombre())) {

                            break;
                        }
                    }
                }
            }
            flag = false;
        }

        if (flag == true) {
            for (int j = 0; j < tutors.size(); j++) {
                if (tutors.get(j) instanceof tutorias) {
                    if (tutors.get(j).getNombre().equals(tutor.getNombre())) {

                        tutors.add(new tutorias(hora, aula, dia, j, dia, clase, tema, tutor));
                        break;

                    }
                } else {
                }
            }
        }
        Object[] newrow2 = {
            hora, aula, dia, clase, mes, año, tema
        };
        DefaultTableModel modelo4 = (DefaultTableModel) tablee.getModel();
        modelo4.addRow(newrow2);
        tablee.setModel(modelo4);
    }//GEN-LAST:event_bt_reservationMouseClicked

    private void bt_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listMouseClicked
        MenuTutores.setVisible(false);
        Listar_tutores.pack();
        Listar_tutores.setModal(true);
        Listar_tutores.setLocationRelativeTo(this);
        Listar_tutores.setVisible(true);
    }//GEN-LAST:event_bt_listMouseClicked

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked

        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_bt_exitMouseClicked

    private void Cb_tutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_tutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_tutoresActionPerformed

    private void Cb_tutoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cb_tutoresItemStateChanged
        if (evt.getStateChange() == 2) {
            tutores s = (tutores) Cb_tutores.getSelectedItem();
            Object[] newrow = {
                s.getNombre(), s.getEdad(), s.getCarrera(), s.getLugar(), s.getCuenta(), s.getUsuario(), s.getPassword(), s.getGanancias(), s.getTutoDadas(), s.getEnseñanza()
            };

            DefaultTableModel modelo = (DefaultTableModel) tablee.getModel();
            modelo.addRow(newrow);
            tablee.setModel(modelo);
        }
    }//GEN-LAST:event_Cb_tutoresItemStateChanged

    private void bt_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_bt_exit1MouseClicked

    private void bt_modificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificar1MouseClicked

    private void bt_chargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_chargeMouseClicked
        String nome, eda, career, lugar, ncuenta, usuario, contraseña;
        nome = txt_nombre.getText().trim();
        eda = txt_edad.getText().trim();
        career = txt_carrera.getText().trim();
        lugar = txt_lugar.getText().trim();
        ncuenta = txt_cuenta.getText().trim();
        usuario = txt_usuario.getText().trim();
        contraseña = txt_password.getText().trim();
        try {

            for (Alumnos o : students) {
                if (o instanceof EstudiantesNormales) {
                     // if (o.getNombre().equals(tf_nombre1)) {
                    Alumnos mod = o;
                    txt_nombre.setText(mod.getNombre());
                    txt_edad.setText(mod.getEdad());
                    txt_carrera.setText(mod.getCarrera());
                    txt_lugar.setText(mod.getLugar());
                    txt_cuenta.setText(mod.getCuenta());
                    txt_usuario.setText(mod.getUsuario());
                    txt_password.setText(mod.getPassword());

                   // }
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Error al cargar datos");
        }


    }//GEN-LAST:event_bt_chargeMouseClicked

    private void bt_modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modifyMouseClicked

        String nome, eda, career, lugar, ncuenta, usuario, contraseña;
        nome = txt_nombre.getText().trim();
        eda = txt_edad.getText().trim();
        career = txt_carrera.getText().trim();
        lugar = txt_lugar.getText().trim();
        ncuenta = txt_cuenta.getText().trim();
        usuario = txt_usuario.getText().trim();
        contraseña = txt_password.getText().trim();
        try {
         
                    //   if (o.getNombre().equals(nome)) {
               
                    tf_nombre1.setText(nome);
                    
                

                    //}
         
            JOptionPane.showMessageDialog(this, " Ha sido modificado exitosamente");
            txt_nombre.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Error al modificar");
        }


    }//GEN-LAST:event_bt_modifyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_Alumnos;
    private javax.swing.JComboBox<String> Cb_tutores;
    private javax.swing.JDialog CrearExamen;
    private javax.swing.JDialog LOGIIN;
    private javax.swing.JDialog Listar_tutores;
    private javax.swing.JDialog MenuEstudiantes;
    private javax.swing.JDialog MenuTutores;
    private javax.swing.JDialog ModificarAlumnos;
    private javax.swing.JDialog RegistroAlumnos;
    private javax.swing.JDialog ReservarTutorias;
    private javax.swing.JButton bt_charge;
    private javax.swing.JButton bt_crearExamen;
    private javax.swing.JButton bt_examenesPendientes;
    private javax.swing.JButton bt_examenesResueltos;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_exit1;
    private javax.swing.JButton bt_iniciar1;
    private javax.swing.JButton bt_list;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_modificar1;
    private javax.swing.JButton bt_modify;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_regresar;
    private javax.swing.JButton bt_reservar;
    private javax.swing.JButton bt_reservation;
    private javax.swing.JButton cb_crearAlumno;
    private javax.swing.JButton cb_crearExamen;
    private javax.swing.JComboBox<String> cb_estudiantes;
    private javax.swing.JButton cb_login;
    private javax.swing.JComboBox<String> cb_tipoAlumno1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondoAlumno;
    private javax.swing.JLabel fondoModi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JDialog listarAlumnos;
    private javax.swing.JDialog modifyStudents;
    private javax.swing.JTable tabi;
    private javax.swing.JTable tabi1;
    private javax.swing.JTable tableExams;
    private javax.swing.JTable tablee;
    private javax.swing.JTextField tf_aula;
    private javax.swing.JTextField tf_carrera1;
    private javax.swing.JTextField tf_clase;
    private javax.swing.JTextField tf_class;
    private javax.swing.JTextField tf_dia;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_hora;
    private javax.swing.JTextField tf_lugar1;
    private javax.swing.JTextField tf_mes;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_numeroCuenta1;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JPasswordField tf_password1;
    private javax.swing.JTextField tf_puntaje;
    private javax.swing.JTextField tf_requerido;
    private javax.swing.JTextField tf_tema;
    private javax.swing.JTextField tf_topic;
    private javax.swing.JTextField tf_user1;
    private javax.swing.JTextField tf_usuario1;
    private javax.swing.JTextField tf_year;
    private javax.swing.JTextField txt_carrera;
    private javax.swing.JTextField txt_cuenta;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_lugar;
    private javax.swing.JTextField txt_nivel;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JDialog verExamenesPendientes;
    private javax.swing.JLabel wallPaper;
    // End of variables declaration//GEN-END:variables

}
